News android 26
EgorVeber/NewsApp pull request #34
Opened 2023-02-18 13:59 UTC by RiValution

NewsAndroid-26 AccountPresenter. Переделать на ViewModel.

2023-02-18 14:11 UTC, EgorVeber requested changes

2023-02-18 14:11 UTC, EgorVeber commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountViewModel.kt
> +    val uiState: LiveData<AccountViewState> = _uiState
Должен быть приватным,

2023-02-18 14:11 UTC, EgorVeber requested changes

2023-02-18 14:11 UTC, EgorVeber commented on app/src/main/java/ru/gb/veber/newsapi/di/AppComponent.kt
>  import ru.gb.veber.newsapi.di.moduls.*
Убрать звездочки

2023-02-18 14:13 UTC, EgorVeber requested changes

2023-02-18 14:13 UTC, EgorVeber commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
>  import ru.gb.veber.newsapi.utils.*
И тут

2023-02-18 14:13 UTC, EgorVeber commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
> +            is AccountViewState.SetBottomNavigationIcon -> {
object без is

2023-02-18 14:20 UTC, aninkina commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
> +class AccountFragment : MvpAppCompatFragment(), BackPressedListener {
MVP)

2023-02-18 14:20 UTC, aninkina commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
> +         binding.privacyPolicy.setOnClickListener {
че пробел нажал?

2023-02-18 14:20 UTC, aninkina commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountViewModel.kt
> +        _uiState.postValue(
поменяй название

2023-02-18 15:39 UTC, aninkina commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountViewModel.kt
> +    data class ShowDialog(
переименуй просто в Dialog

2023-02-18 15:39 UTC, aninkina commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountViewModel.kt
> +        _uiState.postValue(
лучше мб setDialog

2023-02-18 16:34 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountViewModel.kt
> +    val uiState: LiveData<AccountViewState> = _uiState
Исправил

2023-02-18 16:34 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/di/AppComponent.kt
>  import ru.gb.veber.newsapi.di.moduls.*
убрал

2023-02-18 16:34 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
>  import ru.gb.veber.newsapi.utils.*
убрал

2023-02-18 16:34 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
> +            is AccountViewState.SetBottomNavigationIcon -> {
сделал без

2023-02-18 16:34 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
> +class AccountFragment : MvpAppCompatFragment(), BackPressedListener {
убрал

2023-02-18 16:34 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountFragment.kt
> +         binding.privacyPolicy.setOnClickListener {
реформатнул

2023-02-18 16:35 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountViewModel.kt
> +        _uiState.postValue(
переименовал

2023-02-18 16:35 UTC, RiValution commented on app/src/main/java/ru/gb/veber/newsapi/view/profile/account/AccountViewModel.kt
> +    data class ShowDialog(
переименовал

2023-02-18 17:20 UTC, EgorVeber approved these changes

2023-02-19 06:34 UTC, EgorKisel approved these changes

2023-02-19 09:11 UTC, merged